spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/restaurant
    username: postgres
    password: Aibek005

  security:
    jwt:
      secret_key: java16Aibek005

  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
server:
  port: 2005


  error:
    include-message: always